Diplom: part 2
Ekaterina1313/java-explore-with-me pull request #4
Opened 2023-12-09 20:56 UTC by Ekaterina1313

2023-12-13 19:06 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-12-13 19:06 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/mainService/ApiExceptionHandler.java
> +    @ResponseStatus(HttpStatus.BAD_REQUEST)
Два одинаковых метода обработки BAD_REQUEST.
Можно оставить один, а в аннотации прописать несколько классов которые будут методом обрабатываться.

2023-12-13 19:06 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/mainService/controller/Admin/AdminCategoryController.java
> +        log.info("ADMIN-controller: Поступил запрос на добавление новой категории события = " + categoryDto.getName());
В логгере нужно пользоваться `{}` в строке, для подстановки параметров.

2023-12-13 19:06 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/mainService/controller/Admin/AdminCategoryController.java
> +        validName(categoryDto);
Стоить дать более говорящее название... метод кинет исключение если имя не валидно.

2023-12-13 19:06 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/mainService/controller/Admin/AdminCategoryController.java
> +            throw ex;
Тут нужно бросить наше исключение. Подумай, какое подойдет в данной ситуации, или может тебе тесты подскажут.
Кажется это должна быть 500 ошибка...

2023-12-13 19:06 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/mainService/controller/Admin/AdminUserController.java
> +    private void validEmail(UserDto userDto) {
Почему "страдаем" и пишем валидацию вручную и не используем базовые аннотации?

2023-12-13 19:06 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/mainService/mapper/EventMapper.java
> +    private static final DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
Этот форматтер описан у тебя с десяток раз! Вынеси его в одно общедоступное место.

2023-12-13 19:06 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/mainService/service/Admin/AdminUserService.java
> +    public List<UserDto> get(int from, int size, List<Integer> ids) {
```
    public List<UserDto> get(int from, int size, List<Integer> ids) {
        Pageable pageable = PageRequest.of(from, size);

        Page<User> result = (ids == null || ids.isEmpty())
                ? userRepository.findAll(pageable) 
                : userRepository.findUsersById(pageable, ids);

        return result.getContent()
                     .stream()
                     .map(UserMapper::toUserDto)
                     .collect(Collectors.toList());
    }
```

Вот так можно отрефакторить... 
У тебя часть `.getContent().stream().map(UserMapper::toUserDto).collect(Collectors.toList());` была написана дважды.
Да и в целом стремимся к тому чтобы в методе был один `return`

2023-12-13 19:06 UTC, FanaticFiz commented on ewm-service/src/main/java/ru/practicum/mainService/service/Private/PrivateEventService.java
> +        return eventsByUser.getContent().stream().map(EventMapper::toEventFullDto).collect(Collectors.toList());
Не устану повторять - даже если код помещается в одну строку, лучше переносить отдельные операции на новые строки.

```
        return eventsByUser.getContent().stream()
                           .map(EventMapper::toEventFullDto)
                           .collect(Collectors.toList());

```

2023-12-13 19:06 UTC, FanaticFiz commented on ewm-service/src/main/resources/schema.sql
> +
Эти файлы тоже не мешает подравнивать, читается куда проще.

```
CREATE TABLE IF NOT EXISTS participations
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created      TIMESTAMP                                NOT NULL,
    event_id     INTEGER                                  NOT NULL,
    requester_id INTEGER                                  NOT NULL,
    status       VARCHAR(255)                             NOT NULL,
    CONSTRAINT pk_participations PRIMARY KEY (id),
    CONSTRAINT uq_event_request UNIQUE (event_id, requester_id),
    CONSTRAINT fk_event_participation FOREIGN KEY (event_id) REFERENCES events (id),
    CONSTRAINT fk_requester_participation FOREIGN KEY (requester_id) REFERENCES users (id)
);
```

2023-12-13 21:00 UTC, Ekaterina1313 commented on ewm-service/src/main/java/ru/practicum/mainService/controller/Admin/AdminUserController.java
> +    private void validEmail(UserDto userDto) {
я так и сделала и добавила в модел нужные аннотации, но это почему-то не сработало, и ошибки не выбросились. Поэтому и проверила вручную)

2023-12-14 04:19 UTC, FanaticFiz approved these changes

2023-12-14 20:39 UTC, merged